# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Archery < Formula
  desc "psql-style CLI for Archery SQL audit platform (SELECT-only)"
  homepage "https://github.com/rjchien728/archery-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.3.0/archery_0.3.0_darwin_x86_64.tar.gz"
      sha256 "91dc9f2793a770d6a56f3aa110dee66081d59613c100e4967fd707058f9568c6"

      define_method(:install) do
        bin.install "archery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.3.0/archery_0.3.0_darwin_arm64.tar.gz"
      sha256 "3e76086d7239f92cd3347c27b2bc7be00b16a2e1cb590cf47cb4bc2c6958edc9"

      define_method(:install) do
        bin.install "archery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.3.0/archery_0.3.0_linux_x86_64.tar.gz"
      sha256 "45df9dfb8d02f87239172fb240db1db5fa734530e60f2923486ba5ddaf8fa277"
      define_method(:install) do
        bin.install "archery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.3.0/archery_0.3.0_linux_arm64.tar.gz"
      sha256 "f05dbd6b6680685157050317b4a9f9eed2314c3b252a30984e2b92a3ae447c16"
      define_method(:install) do
        bin.install "archery"
      end
    end
  end

  test do
    system "#{bin}/archery", "--version"
  end
end
