# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Archery < Formula
  desc "Psql-style CLI for Archery SQL audit platform (SELECT-only)"
  homepage "https://github.com/rjchien728/archery-cli"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.5.3/archery_0.5.3_darwin_x86_64.tar.gz"
      sha256 "af3203ae0bbc60c85627816d98607bcd9906515e7baf515b15b825c82c8c6471"

      define_method(:install) do
        bin.install "archery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.5.3/archery_0.5.3_darwin_arm64.tar.gz"
      sha256 "e061944906df618f90cdadd535552b4c9eb848998dfd437c84b58e020931c27e"

      define_method(:install) do
        bin.install "archery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.5.3/archery_0.5.3_linux_x86_64.tar.gz"
      sha256 "38311c1bfba17ef5ba38393f9d464d219edb32aa7aa4b701701bedebcead74a7"
      define_method(:install) do
        bin.install "archery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.5.3/archery_0.5.3_linux_arm64.tar.gz"
      sha256 "e85e091a93a7d705ef397b3ca9576e20c087a9d538909376edc187117d69c916"
      define_method(:install) do
        bin.install "archery"
      end
    end
  end

  test do
    system bin/"archery", "--version"
  end
end
