# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Archery < Formula
  desc "Psql-style CLI for Archery SQL audit platform (SELECT-only)"
  homepage "https://github.com/rjchien728/archery-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.3.1/archery_0.3.1_darwin_x86_64.tar.gz"
      sha256 "e9ef386d59ca55baa9178f89fb7b89eb08c4b46c97b98418d2c7e8f4287a45ca"

      define_method(:install) do
        bin.install "archery"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.3.1/archery_0.3.1_darwin_arm64.tar.gz"
      sha256 "2bca9fb452e02375c68cdaf6af2c3a13f852e59e9ec3547c2bb885b32838d747"

      define_method(:install) do
        bin.install "archery"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.3.1/archery_0.3.1_linux_x86_64.tar.gz"
      sha256 "34286230394a6b47286b043aaef00f759b8d39e9a4e9d539bdb7ed8718771693"
      define_method(:install) do
        bin.install "archery"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rjchien728/archery-cli/releases/download/v0.3.1/archery_0.3.1_linux_arm64.tar.gz"
      sha256 "75715db70d4f8ba90fb944e2687382bb2f0fe43de0a12da64715dbcf98b2d0bb"
      define_method(:install) do
        bin.install "archery"
      end
    end
  end

  test do
    system bin/"archery", "--version"
  end
end
